# Generated by Django 5.0.1 on 2024-01-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subasta',
            name='imagen',
            field=models.CharField(max_length=256),
        ),
    ]
