# Generated by Django 5.0.1 on 2024-01-05 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='imagen_perfil',
        ),
    ]
