# Generated by Django 5.0.1 on 2024-01-05 01:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_remove_customuser_imagen_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subasta',
            name='precio_inicial',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.5)]),
        ),
    ]
