# Generated by Django 5.0.1 on 2024-01-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_alter_subasta_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='subasta',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=50.2, max_digits=10),
            preserve_default=False,
        ),
    ]
