# Generated by Django 5.0.1 on 2024-01-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_subasta_precio_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subasta',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
