# Generated by Django 5.0.1 on 2024-01-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_alter_subasta_precio_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subasta',
            name='categoria',
            field=models.CharField(choices=[('Sin especificar', 'Sin especificar'), ('Juguetes', 'Juguetes'), ('Ropa', 'Ropa'), ('Electrónica', 'Electrónica'), ('Hogar', 'Hogar'), ('Colección', 'Colección'), ('Videojuegos', 'Videojuegos'), ('Tecnología', 'Tecnología'), ('Cocina', 'Cocina'), ('Decoración', 'Decoración'), ('Medicina', 'Medicina'), ('Accesorios', 'Accesorios')], max_length=30),
        ),
    ]
